In [1]:
import numpy as np

1.利用NumPy中的eye函数创建一个单位矩阵，即主对角线上的元素均为1，其余元素均为0的正方形矩阵

In [98]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

2.使用array()方法和arange()方法创建一个一维的整数数组，然后使用astype()方法修改数据类型为float,显示数组；抽取数组中值小于0.5的元素，构成一个新的数组；利用reshape()函数把一维数组转换为二维

In [99]:
a=np.array([0.1,0.4,0.3,0.1,1.8,2.4])
b=np.arange(0.1,3,0.05)
a.astype(float)
b.astype(float)
print('a=',a,'\n')
print('b=',b,'\n')

c=a[a<0.5]
d=b[b<0.5]
print('c=',c.reshape(2,2),'\n')
print('d=',d.reshape(4,2),'\n')

a= [0.1 0.4 0.3 0.1 1.8 2.4] 

b= [0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65 0.7  0.75
 0.8  0.85 0.9  0.95 1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35 1.4  1.45
 1.5  1.55 1.6  1.65 1.7  1.75 1.8  1.85 1.9  1.95 2.   2.05 2.1  2.15
 2.2  2.25 2.3  2.35 2.4  2.45 2.5  2.55 2.6  2.65 2.7  2.75 2.8  2.85
 2.9  2.95] 

c= [[0.1 0.4]
 [0.3 0.1]] 

d= [[0.1  0.15]
 [0.2  0.25]
 [0.3  0.35]
 [0.4  0.45]] 



3.numpy数组的切分

In [110]:
A=np.arange(1,13)
A=A.reshape(3,4)
print('A=',A,'\n')
S=np.hsplit(A,[0,3])
B=S[1]
C=S[2]
print('B=',B,'\n')
print('C=',C,'\n')
N=np.vsplit(A,[2,2])
D=N[0]
E=N[2]
print('D=',D,'\n')
print('E=',E,'\n')
print('Max=',np.amax(A,axis=1),'\n')
print('Ave=',np.average(A))

A= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

B= [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]] 

C= [[ 4]
 [ 8]
 [12]] 

D= [[1 2 3 4]
 [5 6 7 8]] 

E= [[ 9 10 11 12]] 

Max= [ 4  8 12] 

Ave= 6.5


4.numpy的常用统计函数

In [119]:
from numpy import random

In [133]:
arr1=random.randint(1,20,size=(3,4))
print(arr1)
print('每一列的和为：',np.sum(arr1,axis=1),'\n')
print('每一行的和为：',np.sum(arr1,axis=0),'\n')
print('每一列中的最小值为：',np.amin(arr1,0),'\n')
print('每一列中的最大值为：',np.amax(arr1,0),'\n')
print('每一列的平均值为：',np.average(arr1,axis=1),'\n')
print('每一行的平均值为：',np.average(arr1,axis=0),'\n')

[[ 5  8 11 16]
 [15  2  9 12]
 [19  9 19  6]]
每一列的和为： [40 38 53] 

每一行的和为： [39 19 39 34] 

每一列中的最小值为： [5 2 9 6] 

每一列中的最大值为： [19  9 19 16] 

每一列的平均值为： [10.    9.5  13.25] 

每一行的平均值为： [13.          6.33333333 13.         11.33333333] 

